# Generated by Django 5.0.6 on 2024-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('Country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_item', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('available_stoke', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('machine_department', models.CharField(max_length=200)),
                ('quantity', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
                ('use_for', models.CharField(max_length=200)),
                ('md_ref', models.CharField(max_length=200)),
                ('sch_date', models.DateField()),
            ],
        ),
    ]
