# Generated by Django 5.0.6 on 2024-07-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_group_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('Country', models.CharField(max_length=200)),
            ],
        ),
    ]
