# Generated by Django 5.0.6 on 2024-07-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_item_tdc_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Grade_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_group', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=200)),
                ('item_group_name', models.CharField(max_length=200)),
                ('color_code', models.CharField(max_length=200)),
            ],
        ),
    ]
