# Generated by Django 5.0.6 on 2024-07-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_item_route_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_parant_FG_Code_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_fg_code', models.CharField(max_length=230)),
            ],
        ),
    ]
