# Generated by Django 5.0.6 on 2024-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_sector_mastere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Section_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=200)),
                ('section_name', models.CharField(max_length=200)),
            ],
        ),
    ]
